apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api
  namespace: twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-api
  template:
    metadata:
      labels:
        app: feed-api
    spec:
      containers:
      - name: feed-api
        image: ghcr.io/dome01/feed_api:latest
        ports:
        - containerPort: 8080
        env:
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SUPABASE_KEY