name: Humble Bee CI/CD
on:
  push:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install -r requirements-test.txt
      - name: Run tests for API1
        run: |
          cd api1
          pytest
      - name: Run tests for API2
        run: |
          cd api2
          pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build and Push
        run: |
          docker build -t ghcr.io/${{ github.repository }}-api1 -f Dockerfile.api1 .
          docker build -t ghcr.io/${{ github.repository }}-api2 -f Dockerfile.api2 .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository }}-api1
          docker push ghcr.io/${{ github.repository }}-api2
