name: Humble Bee CI/CD
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'k8s/**'
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install -r requirements-test.txt
      - name: Run tests for API1
        run: |
          cd api1
          pytest
      - name: Run tests for API2
        run: |
          cd api2
          pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build and push API1 multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api1
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/api1:latest
    
      - name: Build and push API2 multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api2
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/api2:latest
