apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-api
  template:
    metadata:
      labels:
        app: post-api
    spec:
      containers:
      - name: post-api
        image: ghcr.io/dome01/post_api:latest
        ports:
        - containerPort: 8080